"use client";
import { useCallback, useEffect, useState } from "react";
import { browserSupabase } from "@/lib/supabase";
type Profile={id:string;player_id:string;display_name:string;role:string;balance:number;active:boolean;parent_agent_id?:string|null};
type Outcome={name:string;price:number;point?:number}; type Game={id:string;commence_time:string;home_team:string;away_team:string;bookmakers:{key:string;markets:{key:string;outcomes:Outcome[]}[]}[]};
const sports={baseball_mlb:"MLB",basketball_nba:"NBA",americanfootball_nfl:"NFL",icehockey_nhl:"NHL",soccer_epl:"プレミアリーグ",soccer_uefa_champs_league:"CL"};
const jp=(x:string)=>({Draw:"引き分け",Over:"オーバー",Under:"アンダー"} as Record<string,string>)[x]||x;
async function authFetch(path:string,init:RequestInit={}){const {data}=await browserSupabase().auth.getSession();return fetch(path,{...init,headers:{...init.headers,authorization:`Bearer ${data.session?.access_token||""}`}});}
export default function Home(){
 const [profile,setProfile]=useState<Profile|null>(null),[sport,setSport]=useState<keyof typeof sports>("baseball_mlb"),[games,setGames]=useState<Game[]>([]),[message,setMessage]=useState("更新中"),[adminOpen,setAdminOpen]=useState(false),[agentOpen,setAgentOpen]=useState(false);
 const load=useCallback(async()=>{const w=await authFetch("/api/wallet");if(w.status===401){location.href="/login";return}const wd=await w.json();if(!w.ok){setMessage(wd.error);return}setProfile(wd.profile);setMessage("更新中");const o=await fetch(`/api/odds?sport=${sport}`,{cache:"no-store"});const od=await o.json();if(o.ok){setGames(od.games||[]);setMessage(`最終更新 ${new Date().toLocaleTimeString("ja-JP")}`)}else setMessage(od.error);},[sport]);
 useEffect(()=>{load();const t=setInterval(()=>{if(!document.hidden)load()},60000);return()=>clearInterval(t)},[load]); async function logout(){await browserSupabase().auth.signOut();location.href="/login"}
 return <main className="shell"><header><div><h1>▲ スポーツベットドット</h1><p>無料ポイント専用</p></div><button onClick={logout}>ログアウト</button></header>{profile&&<section className="wallet"><div><span>{profile.display_name}</span><b>{Number(profile.balance).toLocaleString()}pt</b></div><div className="wallet-actions">{profile.role==="admin"&&<button onClick={()=>setAdminOpen(!adminOpen)}>全体管理</button>}{["admin","agent"].includes(profile.role)&&<button onClick={()=>setAgentOpen(!agentOpen)}>エージェント管理</button>}</div></section>}{adminOpen&&profile?.role==="admin"&&<AdminPanel/>}{agentOpen&&profile&&["admin","agent"].includes(profile.role)&&<AgentPanel onChanged={load}/>}<section className="controls"><label>競技<select value={sport} onChange={e=>setSport(e.target.value as keyof typeof sports)}>{Object.entries(sports).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div>自動更新 <b>1分ごと</b></div><button onClick={load}>今すぐ更新</button></section><div className="heading"><h2>{sports[sport]} オッズ</h2><p>{message}</p></div><section className="games">{games.map(g=><GameCard key={g.id} game={g}/>)}</section><footer>ポイントの購入・換金・譲渡・景品交換はできません。</footer></main>;
}
function GameCard({game}:{game:Game}){const book=game.bookmakers.find(b=>b.key==="pinnacle")||game.bookmakers[0];const market=(key:string)=>book?.markets.find(m=>m.key===key)?.outcomes||[];return <article className="game"><div className="gamehead"><span>{new Date(game.commence_time).toLocaleString("ja-JP")}</span><span>オッズ表示</span></div><div className="match"><b>{game.away_team}</b><span>vs</span><b>{game.home_team}</b></div>{[["勝敗",market("h2h")],["ハンデ",market("spreads")],["合計点",market("totals")]].map(([title,items])=><div className="market" key={title as string}><h3>{title as string}</h3>{(items as Outcome[]).map(o=><div className="odd" key={`${o.name}${o.point}`}><span>{jp(o.name)}{o.point==null?"":` ${o.point>0?"+":""}${o.point}`}</span><b>{o.price.toFixed(2)}</b></div>)}</div>)}</article>}
function AgentPanel({onChanged}:{onChanged:()=>void}){const [members,setMembers]=useState<Profile[]>([]),[id,setId]=useState(""),[name,setName]=useState(""),[pass,setPass]=useState(""),[amount,setAmount]=useState(1000),[target,setTarget]=useState(""),[msg,setMsg]=useState("");const load=useCallback(async()=>{const r=await authFetch("/api/agent");const d=await r.json();if(r.ok){setMembers(d.members);setTarget(x=>d.members.some((m:Profile)=>m.id===x)?x:(d.members[0]?.id||""))}else setMsg(d.error)},[]);useEffect(()=>{load()},[load]);async function post(body:unknown){setMsg("");const r=await authFetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMsg(r.ok?"完了しました":d.error);if(r.ok){load();onChanged()}}return <section className="admin agent"><h2>エージェント管理</h2><p className="hint">あなたの配下プレイヤーだけを管理できます。</p><div className="create"><input placeholder="プレイヤーID" value={id} onChange={e=>setId(e.target.value)}/><input placeholder="表示名" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="初期パスワード（8文字以上）" type="password" value={pass} onChange={e=>setPass(e.target.value)}/><button onClick={()=>post({action:"create",playerId:id,displayName:name,password:pass})}>配下を作成</button></div>{members.length>0&&<div className="adjust"><select value={target} onChange={e=>setTarget(e.target.value)}>{members.map(u=><option key={u.id} value={u.id}>{u.display_name}（{u.balance.toLocaleString()}pt）</option>)}</select><input type="number" min="1" value={amount} onChange={e=>setAmount(Math.abs(Number(e.target.value)))}/><button onClick={()=>post({action:"transfer",userId:target,amount})}>送る</button><button className="danger" onClick={()=>post({action:"transfer",userId:target,amount:-amount})}>回収</button></div>}{msg&&<p className="panel-message">{msg}</p>}<div className="users">{members.length===0?<p className="empty">配下プレイヤーはまだいません</p>:members.map(u=><div key={u.id}><span><b>{u.display_name}</b><small>{u.player_id}</small></span><strong>{u.balance.toLocaleString()}pt</strong><button onClick={()=>post({action:"toggle",userId:u.id,active:!u.active})}>{u.active?"停止":"再開"}</button></div>)}</div></section>}
function AdminPanel(){const [users,setUsers]=useState<Profile[]>([]),[id,setId]=useState(""),[name,setName]=useState(""),[pass,setPass]=useState(""),[role,setRole]=useState("agent"),[amount,setAmount]=useState(1000),[target,setTarget]=useState(""),[msg,setMsg]=useState("");const load=useCallback(async()=>{const r=await authFetch("/api/admin");const d=await r.json();if(r.ok){setUsers(d.users);setTarget(x=>x||d.users?.[0]?.id||"")}else setMsg(d.error)},[]);useEffect(()=>{load()},[load]);async function post(body:unknown){setMsg("");const r=await authFetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMsg(r.ok?"完了しました":d.error);if(r.ok)load()}return <section className="admin"><h2>全体管理</h2><div className="create admin-create"><select value={role} onChange={e=>setRole(e.target.value)}><option value="agent">エージェント</option><option value="player">プレイヤー</option></select><input placeholder="ログインID" value={id} onChange={e=>setId(e.target.value)}/><input placeholder="表示名" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="初期パスワード（8文字以上）" type="password" value={pass} onChange={e=>setPass(e.target.value)}/><button onClick={()=>post({action:"create",playerId:id,displayName:name,password:pass,role})}>作成</button></div><div className="adjust"><select value={target} onChange={e=>setTarget(e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.display_name}（{u.role}・{u.balance.toLocaleString()}pt）</option>)}</select><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><button onClick={()=>post({action:"adjust",userId:target,amount})}>付与</button><button className="danger" onClick={()=>post({action:"adjust",userId:target,amount:-amount})}>回収</button></div>{msg&&<p>{msg}</p>}<div className="users">{users.map(u=><div key={u.id}><span><b>{u.display_name}</b><small>{u.player_id} ・ {u.role}</small></span><strong>{u.balance.toLocaleString()}pt</strong>{u.role!=="admin"&&<button onClick={()=>post({action:"toggle",userId:u.id,active:!u.active})}>{u.active?"停止":"再開"}</button>}</div>)}</div></section>}
