"use client";
import {useCallback,useEffect,useState} from "react";
import {browserSupabase} from "@/lib/supabase";
import {AdminPanel,AgentPanel,Profile,authFetch} from "./admin-panels";

type Outcome={name:string;price:number;point?:number};
type Game={id:string;commence_time:string;home_team:string;away_team:string;sport_key:string;league_name?:string;bookmakers:{key:string;markets:{key:string;outcomes:Outcome[]}[]}[]};
type Bet={id:string;commence_time:string;home_team:string;away_team:string;market_key:string;selection_name:string;point:number|null;odds:number;stake:number;potential_payout:number;status:string;result:string|null};
type Slip={game:Game;sportKey:string;marketKey:string;outcome:Outcome};
const sports={baseball_mlb:"MLB",basketball_nba:"NBA",americanfootball_nfl:"NFL",icehockey_nhl:"NHL",soccer:"サッカー"};
const jp=(x:string)=>({Draw:"引き分け",Over:"オーバー",Under:"アンダー"} as Record<string,string>)[x]||x;
const marketName=(x:string)=>({h2h:"勝敗",spreads:"ハンデ",totals:"合計点"} as Record<string,string>)[x]||x;
const selection=(name:string,point?:number|null)=>`${jp(name)}${point==null?"":` ${point>0?"+":""}${point}`}`;

export default function Home(){
 const [profile,setProfile]=useState<Profile|null>(null),[sport,setSport]=useState<keyof typeof sports>("baseball_mlb"),[games,setGames]=useState<Game[]>([]),[bets,setBets]=useState<Bet[]>([]),[message,setMessage]=useState("更新中"),[adminOpen,setAdminOpen]=useState(false),[agentOpen,setAgentOpen]=useState(false),[betsOpen,setBetsOpen]=useState(false),[slip,setSlip]=useState<Slip|null>(null);
 const load=useCallback(async()=>{const w=await authFetch("/api/wallet");if(w.status===401){location.href="/login";return}const wd=await w.json();if(!w.ok){setMessage(wd.error);return}setProfile(wd.profile);setBets(wd.bets||[]);setMessage("更新中");const [o,b]=await Promise.all([fetch(`/api/odds?sport=${sport}`,{cache:"no-store"}),authFetch("/api/bets")]);const [od,bd]=await Promise.all([o.json(),b.json()]);if(o.ok){setGames(od.games||[]);setMessage(`最終更新 ${new Date().toLocaleTimeString("ja-JP")}`)}else setMessage(od.error);if(b.ok)setBets(bd.bets||[])},[sport]);
 useEffect(()=>{load();const t=setInterval(()=>{if(!document.hidden)load()},60000);return()=>clearInterval(t)},[load]);
 async function logout(){await browserSupabase().auth.signOut();location.href="/login"}
 const pending=bets.filter(b=>b.status==="pending").length;
 return <main className="shell"><header><h1>▲ スポーツベットドット</h1><button onClick={logout}>ログアウト</button></header>{profile&&<section className="wallet"><div><span>{profile.display_name}</span><b>{Number(profile.balance).toLocaleString()}pt</b></div><div className="wallet-actions"><button onClick={()=>setBetsOpen(!betsOpen)}>マイベット{pending?` (${pending})`:""}</button>{profile.role==="admin"&&<button onClick={()=>setAdminOpen(!adminOpen)}>全体管理</button>}{["admin","agent"].includes(profile.role)&&<button onClick={()=>setAgentOpen(!agentOpen)}>エージェント管理</button>}</div></section>}{betsOpen&&<MyBets bets={bets}/>} {adminOpen&&profile?.role==="admin"&&<AdminPanel/>}{agentOpen&&profile&&["admin","agent"].includes(profile.role)&&<AgentPanel onChanged={load}/>}<section className="controls"><label>競技<select value={sport} onChange={e=>setSport(e.target.value as keyof typeof sports)}>{Object.entries(sports).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div>自動更新 <b>1分ごと</b></div><button onClick={load}>今すぐ更新</button></section><div className="heading"><h2>{sports[sport]} オッズ</h2><p>{message}</p></div><section className="games">{games.map(g=><GameCard key={`${g.sport_key}-${g.id}`} game={g} onPick={setSlip}/>)}</section><footer>ポイントの購入・換金・譲渡・景品交換はできません。</footer>{slip&&profile&&<BetSlip slip={slip} balance={Number(profile.balance)} onClose={()=>setSlip(null)} onPlaced={async()=>{setSlip(null);setBetsOpen(true);await load()}}/>}</main>
}

function GameCard({game,onPick}:{game:Game;onPick:(s:Slip)=>void}){const book=game.bookmakers.find(b=>b.key==="pinnacle")||game.bookmakers[0];const get=(key:string)=>book?.markets.find(m=>m.key===key)?.outcomes||[];return <article className="game"><div className="gamehead"><span>{new Date(game.commence_time).toLocaleString("ja-JP")}</span><span>{game.league_name||"オッズを選択"}</span></div><div className="match"><b>{game.away_team}</b><span>vs</span><b>{game.home_team}</b></div>{[["勝敗","h2h",get("h2h")],["ハンデ","spreads",get("spreads")],["合計点","totals",get("totals")]].map(([title,key,items])=><div className="market" key={key as string}><h3>{title as string}</h3>{(items as Outcome[]).map(o=><button type="button" className="odd odd-button" key={`${o.name}${o.point}`} onClick={()=>onPick({game,sportKey:game.sport_key,marketKey:key as string,outcome:o})}><span>{selection(o.name,o.point)}</span><b>{o.price.toFixed(2)}</b></button>)}</div>)}</article>}

function BetSlip({slip,balance,onClose,onPlaced}:{slip:Slip;balance:number;onClose:()=>void;onPlaced:()=>void}){const [stake,setStake]=useState("100"),[busy,setBusy]=useState(false),[error,setError]=useState("");const stakeValue=Number(stake||0),payout=Math.floor(Math.max(0,stakeValue)*slip.outcome.price);async function submit(){if(!Number.isInteger(stakeValue)||stakeValue<1||stakeValue>balance){setError(stakeValue>balance?"保有ポイントが不足しています":"1pt以上を入力してください");return}setBusy(true);setError("");const r=await authFetch("/api/bets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:slip.game.id,sportKey:slip.sportKey,marketKey:slip.marketKey,selectionName:slip.outcome.name,point:slip.outcome.point??null,stake:stakeValue})});const d=await r.json();if(!r.ok){setError(d.error||"確定できませんでした");setBusy(false);return}await onPlaced()}return <div className="slip-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="bet-slip" role="dialog" aria-modal="true" aria-labelledby="slip-title"><div className="slip-head"><div><small>{marketName(slip.marketKey)}</small><h2 id="slip-title">{selection(slip.outcome.name,slip.outcome.point)}</h2></div><button className="close-button" onClick={onClose} aria-label="閉じる">×</button></div><p className="slip-match">{slip.game.away_team} vs {slip.game.home_team}</p><div className="slip-odds"><span>オッズ</span><b>{slip.outcome.price.toFixed(2)}</b></div><label className="stake-field">賭けるポイント<input inputMode="numeric" type="text" value={stake} onChange={e=>setStake(e.target.value.replace(/\D/g,"").replace(/^0+(?=\d)/,""))}/></label><div className="quick-stakes">{[100,500,1000].map(n=><button key={n} onClick={()=>setStake(String(Math.min(n,balance)))}>{n.toLocaleString()}pt</button>)}<button onClick={()=>setStake(String(balance))}>全額</button></div><div className="slip-summary"><span>保有 {balance.toLocaleString()}pt</span><strong>受取予定 {payout.toLocaleString()}pt</strong></div>{error&&<p className="error">{error}</p>}<button className="place-bet" disabled={busy||balance<1} onClick={submit}>{busy?"確定中…":"予想を確定"}</button><small className="slip-note">確定後は取り消せません。</small></section></div>}

function MyBets({bets}:{bets:Bet[]}){const label=(b:Bet)=>b.status==="pending"?"結果待ち":b.result==="win"?"的中":b.result==="push"?"返還":"不的中";return <section className="my-bets"><div className="panel-title"><h2>マイベット</h2><span>{bets.length}件</span></div>{bets.length===0?<p className="empty">予想履歴はまだありません</p>:<div className="bet-list">{bets.map(b=><article key={b.id} className={`bet-row ${b.status==="settled"?b.result:"pending"}`}><div className="bet-row-top"><span>{new Date(b.commence_time).toLocaleString("ja-JP")}</span><b>{label(b)}</b></div><strong>{selection(b.selection_name,b.point)}</strong><small>{b.away_team} vs {b.home_team} ・ {marketName(b.market_key)}</small><div className="bet-numbers"><span>{Number(b.stake).toLocaleString()}pt × {Number(b.odds).toFixed(2)}</span><span>受取予定 {Number(b.potential_payout).toLocaleString()}pt</span></div></article>)}</div>}</section>}
